spring:
  datasource:
    url: jdbc:h2:file:./data/camunda-h2-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    generic-properties:
      properties:
        historyTimeToLive: 5


